const data = [
  {
    bbb: null,
    ccc: false,
    ddd: 123,
    eee: 'str',
    name: {
      first: 'Stacie',
      last: 'Anthony',
      name: {
        first: 'Stacie',
        last: 'Anthony',
        name: {
          first: 'Stacie',
          last: 'Anthony',
          name: {
            first: 'Stacie',
            last: 'Anthony',
          },
        },
      },
    },
    friends: [
      {
        id: 0,
        name: 'Schroeder Gill',
        friends: [
          {
            id: 0,
            name: 'Schroeder Gill',
            friends2: [
              {
                id: 0,
                name: 'Schroeder Gill',
              },
              {
                id: 1,
                name: 'Downs Burton',
              },
              {
                id: 2,
                name: 'Gertrude Schneider',
                friends3: [
                  {
                    id: 0,
                    name: 'Schroeder Gill',
                  },
                  {
                    id: 1,
                    name: 'Downs Burton',
                  },
                  {
                    id: 2,
                    name: 'Gertrude Schneider',
                  },
                ],
              },
            ],
          },
          {
            id: 1,
            name: 'Downs Burton',
          },
          {
            id: 2,
            name: 'Gertrude Schneider',
          },
        ],
      },
      {
        id: 1,
        name: 'Downs Burton',
      },
      {
        id: 2,
        name: 'Gertrude Schneider',
      },
    ],
    _id: '5f0a9cfe35dfcba5afc17b7a',
    index: 0,
    guid: '08871bf9-871d-45ed-961d-9db598eaca04',
    isActive: true,
    balance: '$1,717.84',
    picture: 'http://placehold.it/32x32',
    age: 30,
    eyeColor: 'blue',
    company: 'SAVVY',
    email: 'stacie.anthony@savvy.net',
    phone: '+1 (878) 435-2874',
    address: '891 Garden Street, Tedrow, Tennessee, 8201',
    about:
      'Veniam id eu nisi commodo Lorem labore mollit consectetur proident ullamco dolor. Consectetur non reprehenderit veniam est esse ex sunt enim adipisicing sint. Enim sit nostrud dolor veniam dolore exercitation do qui. Consectetur ullamco consectetur id Lorem cupidatat qui velit tempor reprehenderit dolore deserunt. Aute dolore excepteur ipsum et reprehenderit ullamco. Ex consequat aliqua ea laborum consectetur qui.',
    registered: 'Thursday, October 10, 2019 7:06 AM',
    latitude: '34.61686',
    longitude: '146.427886',
    tags: ['velit', 'occaecat', 'sunt', 'dolore', 'Lorem'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    greeting: 'Hello, Stacie! You have 9 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '5f0a9cfe1e8873f5fdf73d52',
    index: 1,
    guid: '764b8dd7-53db-4fa2-ab9d-5c82e5af139b',
    isActive: true,
    balance: '$2,825.43',
    picture: 'http://placehold.it/32x32',
    age: 31,
    eyeColor: 'brown',
    name: {
      first: 'Mccray',
      last: 'Long',
    },
    company: 'CONFRENZY',
    email: 'mccray.long@confrenzy.com',
    phone: '+1 (969) 524-2227',
    address: '915 Lincoln Place, Winfred, Iowa, 1488',
    about:
      'Eiusmod consequat sint elit ex adipisicing. Fugiat adipisicing officia consequat laboris laborum ut occaecat. Exercitation minim et fugiat nisi incididunt et enim incididunt dolor est.',
    registered: 'Friday, September 19, 2014 3:27 PM',
    latitude: '25.442916',
    longitude: '12.444934',
    tags: ['laborum', 'ex', 'dolor', 'mollit', 'laboris'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Martha Richmond',
      },
      {
        id: 1,
        name: 'Landry Mitchell',
      },
      {
        id: 2,
        name: 'Hendricks Dunn',
      },
    ],
    greeting: 'Hello, Mccray! You have 6 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5f0a9cfe5f7be7e7c0a00e0b',
    index: 2,
    guid: 'd7ab0c3b-dbc1-4c75-b886-af8d3cd98415',
    isActive: true,
    balance: '$3,091.72',
    picture: 'http://placehold.it/32x32',
    age: 27,
    eyeColor: 'blue',
    name: {
      first: 'Vilma',
      last: 'Carroll',
    },
    company: 'ENDICIL',
    email: 'vilma.carroll@endicil.co.uk',
    phone: '+1 (854) 564-3833',
    address: '841 Linden Street, Saranap, Montana, 9760',
    about:
      'Officia est proident et aliquip deserunt aliquip. Ipsum cillum ad incididunt excepteur consectetur magna sint dolore qui quis. Labore voluptate laborum consequat velit duis occaecat aliqua eu laborum tempor minim veniam tempor. Et exercitation et ex eu et eiusmod. Et do magna et amet sit exercitation nulla sunt Lorem nostrud consectetur aliqua. Eu id sint tempor aliqua sint velit excepteur.',
    registered: 'Friday, December 8, 2017 1:22 PM',
    latitude: '-83.30078',
    longitude: '-31.272798',
    tags: ['in', 'tempor', 'ex', 'cillum', 'eiusmod'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Burt Hutchinson',
      },
      {
        id: 1,
        name: 'Aurora Pennington',
      },
      {
        id: 2,
        name: 'Terra Cox',
      },
    ],
    greeting: 'Hello, Vilma! You have 6 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '5f0a9cfeac537c26c222d4b9',
    index: 3,
    guid: '2ddb623c-7776-4f0b-9ef2-e724434f7f7c',
    isActive: true,
    balance: '$3,597.60',
    picture: 'http://placehold.it/32x32',
    age: 23,
    eyeColor: 'green',
    name: {
      first: 'Alma',
      last: 'Velez',
    },
    company: 'ORBIXTAR',
    email: 'alma.velez@orbixtar.biz',
    phone: '+1 (925) 428-3533',
    address: '486 Classon Avenue, Eagletown, Kansas, 1462',
    about:
      'Culpa voluptate aliqua veniam quis proident et exercitation ipsum est do. Consequat reprehenderit officia veniam excepteur dolor id nisi cupidatat laboris est quis dolor dolore nostrud. Fugiat pariatur minim culpa occaecat sint et voluptate consequat esse. Est commodo amet dolore excepteur irure elit aute fugiat esse velit sint aliquip. Est labore proident ipsum proident. Qui tempor veniam pariatur magna laborum et velit duis occaecat non eiusmod. Adipisicing sunt officia sunt eiusmod eu dolore amet sunt proident aute in veniam laborum.',
    registered: 'Monday, April 20, 2020 10:10 AM',
    latitude: '19.326973',
    longitude: '-25.365487',
    tags: ['ex', 'ut', 'ipsum', 'consequat', 'Lorem'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Watts Roman',
      },
      {
        id: 1,
        name: 'Nolan Greer',
      },
      {
        id: 2,
        name: 'Moody Russo',
      },
    ],
    greeting: 'Hello, Alma! You have 7 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '5f0a9cfe15e8e2571c77f5a8',
    index: 4,
    guid: '3e3b1e97-b9e4-44aa-877c-7a9250a0be83',
    isActive: true,
    balance: '$2,348.86',
    picture: 'http://placehold.it/32x32',
    age: 35,
    eyeColor: 'brown',
    name: {
      first: 'Staci',
      last: 'Nolan',
    },
    company: 'SONGBIRD',
    email: 'staci.nolan@songbird.org',
    phone: '+1 (945) 401-2174',
    address: '657 Monroe Place, Northchase, New Mexico, 1063',
    about:
      'Qui aute esse et adipisicing veniam et elit proident commodo nisi qui. Nulla irure eu id dolor deserunt aliqua. Do cillum qui est ad.',
    registered: 'Thursday, February 18, 2016 6:28 PM',
    latitude: '64.188798',
    longitude: '99.065898',
    tags: ['cupidatat', 'ullamco', 'commodo', 'sit', 'et'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Brandi Scott',
      },
      {
        id: 1,
        name: 'Workman Barnes',
      },
      {
        id: 2,
        name: 'Dotson Walsh',
      },
    ],
    greeting: 'Hello, Staci! You have 8 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '5f0a9cfedf35d9094bd7ed58',
    index: 5,
    guid: '4bd624fb-5c0a-4d67-80d9-d6033568f1e0',
    isActive: true,
    balance: '$3,844.96',
    picture: 'http://placehold.it/32x32',
    age: 26,
    eyeColor: 'blue',
    name: {
      first: 'Sheri',
      last: 'Leblanc',
    },
    company: 'ENDIPIN',
    email: 'sheri.leblanc@endipin.name',
    phone: '+1 (810) 562-3600',
    address: '184 Dobbin Street, Chaparrito, Guam, 9738',
    about:
      'Sit irure culpa reprehenderit aliqua officia magna et esse officia mollit non irure duis veniam. Cupidatat cillum magna ut amet cupidatat pariatur in magna occaecat est amet laboris. Fugiat eiusmod adipisicing aute officia est ea duis esse sint consequat Lorem adipisicing voluptate. Adipisicing tempor veniam exercitation occaecat aliquip est culpa ea laboris ex elit. Veniam aute minim deserunt ut nisi cillum commodo mollit quis.',
    registered: 'Wednesday, February 7, 2018 9:46 AM',
    latitude: '-19.548184',
    longitude: '-145.989058',
    tags: ['ipsum', 'ex', 'pariatur', 'ipsum', 'consequat'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Abigail Bennett',
      },
      {
        id: 1,
        name: 'Willis Massey',
      },
      {
        id: 2,
        name: 'Elisa Leonard',
      },
    ],
    greeting: 'Hello, Sheri! You have 7 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '5f0a9cfe6a7d6b80e8ecbff8',
    index: 6,
    guid: 'fc2bf1d5-97ea-4fe3-9682-003be05c6e3a',
    isActive: true,
    balance: '$3,003.20',
    picture: 'http://placehold.it/32x32',
    age: 37,
    eyeColor: 'green',
    name: {
      first: 'Kristen',
      last: 'Larson',
    },
    company: 'COMTEXT',
    email: 'kristen.larson@comtext.me',
    phone: '+1 (999) 547-3586',
    address: '436 Manor Court, Wiscon, Michigan, 2067',
    about:
      'Enim minim mollit mollit exercitation enim veniam. Aliquip cillum sunt occaecat anim cupidatat magna nulla adipisicing commodo dolor. Fugiat consequat id dolor Lorem. Quis consequat do veniam ut ut enim qui dolore et quis sint veniam et ea. Nulla non sint dolor aliqua veniam elit reprehenderit aliquip eiusmod ad consequat. Sit excepteur laboris consectetur dolor duis do minim do Lorem.',
    registered: 'Saturday, April 25, 2020 2:07 PM',
    latitude: '-73.324641',
    longitude: '-129.841662',
    tags: ['excepteur', 'nisi', 'tempor', 'tempor', 'sint'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Andrews Blackwell',
      },
      {
        id: 1,
        name: 'Kristie Myers',
      },
      {
        id: 2,
        name: 'Schultz Langley',
      },
    ],
    greeting: 'Hello, Kristen! You have 6 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5f0a9cfe2a4428e9bbf5be45',
    index: 7,
    guid: '58a42bc6-d374-42d2-a7bf-7633f16f1b4b',
    isActive: false,
    balance: '$1,114.27',
    picture: 'http://placehold.it/32x32',
    age: 35,
    eyeColor: 'blue',
    name: {
      first: 'Neva',
      last: 'Hatfield',
    },
    company: 'FLUMBO',
    email: 'neva.hatfield@flumbo.info',
    phone: '+1 (824) 421-2952',
    address: '603 Conselyea Street, Chalfant, Wisconsin, 5461',
    about:
      'Ut adipisicing exercitation do id dolore consectetur. Consequat laboris irure nostrud non irure fugiat aute adipisicing ad amet dolor cupidatat. Do excepteur adipisicing sunt do.',
    registered: 'Tuesday, June 20, 2017 5:10 PM',
    latitude: '60.409837',
    longitude: '-36.876068',
    tags: ['sit', 'quis', 'amet', 'ea', 'deserunt'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Casey Davidson',
      },
      {
        id: 1,
        name: 'Miles Good',
      },
      {
        id: 2,
        name: 'Bernice Wells',
      },
    ],
    greeting: 'Hello, Neva! You have 7 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '5f0a9cfe49bb4abe9050c2c4',
    index: 8,
    guid: '06560c8b-54f3-4cf1-a1ea-06da38364a37',
    isActive: false,
    balance: '$1,225.97',
    picture: 'http://placehold.it/32x32',
    age: 27,
    eyeColor: 'brown',
    name: {
      first: 'Lenora',
      last: 'Mcfarland',
    },
    company: 'ECRAZE',
    email: 'lenora.mcfarland@ecraze.tv',
    phone: '+1 (847) 423-2833',
    address:
      '564 Willoughby Avenue, Shindler, Federated States Of Micronesia, 3203',
    about:
      'Fugiat quis tempor sit sunt. Consectetur anim irure adipisicing officia cupidatat fugiat fugiat nisi irure elit. Est commodo et Lorem ipsum labore. Ut in tempor pariatur incididunt ea Lorem duis sit esse.',
    registered: 'Monday, June 25, 2018 9:10 PM',
    latitude: '-63.901607',
    longitude: '-19.551159',
    tags: ['elit', 'et', 'magna', 'proident', 'incididunt'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Pittman Marsh',
      },
      {
        id: 1,
        name: 'Tyler Love',
      },
      {
        id: 2,
        name: 'Celina Davis',
      },
    ],
    greeting: 'Hello, Lenora! You have 6 unread messages.',
    favoriteFruit: 'banana',
  },
]
